// ────────────────────────────────────────────────────────────
//  Attack chains — multi-step playbooks
//  Each chain is tagged with a category/subcategory so the
//  sidebar can filter it. Steps reference command ids via cmdRef.
// ────────────────────────────────────────────────────────────

const CHAINS = [
  {
    id: 'passive-subs',
    name: 'Passive Subdomain Discovery',
    short: 'subs',
    category: 'info-gathering', subcategory: 'passive-recon',
    tactic: 'Reconnaissance',
    difficulty: 'easy',
    estTime: '10 min',
    objective: 'Enumerare il massimo dei sottodomini SENZA toccare il target: aggrega più fonti passive, unisci le liste e risolvile per ottenere solo gli host vivi.',
    outcome: 'Lista di sottodomini vivi (host + IP) pronta per la fase active',
    prereqs: [
      'Solo il dominio root',
      'API key per subfinder/chaos = copertura migliore (opzionale)',
    ],
    mitre: ['T1590.002', 'T1596.001'],
    steps: [
      { id: 's1', title: 'CT logs (crt.sh)',
        cmdRef: 'crtsh',
        rationale: 'I certificati pubblici espongono sottodomini, anche dev/staging. Zero traffico al target.',
        captures: [{ key: 'subs', label: 'Sub da CT' }],
        verify: 'crtsh.txt non è vuoto.' },
      { id: 's2', title: 'subfinder (-all)',
        cmdRef: 'subfinder',
        rationale: 'Aggrega decine di fonti passive oltre ai CT log.' },
      { id: 's3', title: 'amass passivo',
        cmdRef: 'amass-passive',
        rationale: 'Altre fonti ancora: amass trova spesso sub che gli altri perdono.' },
      { id: 's4', title: 'assetfinder',
        cmdRef: 'assetfinder',
        rationale: 'Raccolta veloce extra — più fonti = più copertura.' },
      { id: 's5', title: 'Unisci e risolvi',
        cmdRef: 'dnsx-resolve',
        rationale: 'cat di tutti i .txt, dedup e risoluzione: tieni solo gli host vivi con record A.',
        captures: [{ key: 'live', label: 'Host vivi + IP' }] },
    ],
  },
  {
    id: 'passive-footprint',
    name: 'Passive Domain Footprint',
    short: 'recon',
    category: 'info-gathering', subcategory: 'passive-recon',
    tactic: 'Reconnaissance',
    difficulty: 'easy',
    estTime: '20 min',
    objective: 'Costruisci una mappa esterna completa del dominio SENZA inviargli traffico: dati di registrazione, DNS, sottodomini, email e servizi esposti, tutto da fonti terze.',
    outcome: 'Lista sottodomini + host vivi + email/naming convention + porte esposte',
    prereqs: [
      'Serve solo il dominio root',
      'Le API key (Shodan, fonti subfinder) migliorano la copertura (opzionale)',
    ],
    mitre: ['T1590', 'T1591', 'T1596', 'T1589.002'],
    steps: [
      { id: 's1', title: 'Registrazione e nameserver',
        cmdRef: 'whois-domain',
        rationale: 'Registrar, date e record NS: i nameserver rivelano il provider DNS/hosting.',
        captures: [{ key: 'registrar', label: 'Registrar / NS' }] },
      { id: 's2', title: 'Record DNS',
        cmdRef: 'dig-records',
        rationale: 'MX/TXT rivelano il mail provider, SPF/DKIM e i SaaS usati dall’organizzazione.',
        captures: [{ key: 'mx', label: 'Mail provider (MX)' }] },
      { id: 's3', title: 'Sottodomini dai CT logs',
        cmdRef: 'crtsh',
        rationale: 'I Certificate Transparency espongono sottodomini (anche dev/staging) senza traffico al target.',
        captures: [{ key: 'subs', label: 'Sub dai CT' }],
        verify: 'crtsh.txt non è vuoto.' },
      { id: 's4', title: 'Aggrega altri sottodomini',
        cmdRef: 'subfinder',
        rationale: 'Aggiunge fonti passive oltre ai CT log. Unisci con crt.sh / amass / assetfinder in all_subs.txt.' },
      { id: 's5', title: 'Risolvi agli host vivi',
        cmdRef: 'dnsx-resolve',
        rationale: 'Trasforma la lista unita in record A vivi: diventa la lista target della fase active.',
        captures: [{ key: 'live', label: 'Host vivi + IP' }] },
      { id: 's6', title: 'Email e naming convention',
        cmdRef: 'theharvester',
        rationale: 'Le email raccolte rivelano il pattern username (n.cognome, nome.cognome…) per lo spraying.',
        captures: [{ key: 'emails', label: 'Email / pattern' }] },
      { id: 's7', title: 'Servizi esposti (no touch)',
        cmdRef: 'shodan-host',
        rationale: 'Scegli un IP vivo dallo step 5 (mettilo nel Target). Shodan mostra porte/CVE senza scansionare.' },
    ],
  },
  {
    id: 'esc1-to-da',
    name: 'ADCS ESC1 → Domain Admin',
    short: 'esc1',
    category: 'active-directory', subcategory: 'priv-esc',
    tactic: 'Privilege Escalation',
    difficulty: 'medium',
    estTime: '15 min',
    objective: 'Escalate from any authenticated domain user to Domain Admin by abusing a misconfigured certificate template (ESC1 — client auth + low-priv enroll + supplied SAN).',
    outcome: 'NT hash of Administrator / DA ticket',
    prereqs: [
      'Valid creds for any domain user',
      'Network access to a DC and to ADCS',
      'At least one vulnerable template exists',
    ],
    mitre: ['T1649', 'T1078.002'],
    steps: [
      { id: 's1', title: 'Enumerate vulnerable ADCS templates',
        cmdRef: 'certipy-find',
        rationale: 'List CAs and flag templates allowing client auth + low-priv enrollment + SAN supply. Look for ESC1 in the output.',
        captures: [
          { key: 'ca',       label: 'CA name',        hint: 'CORP-CA' },
          { key: 'template', label: 'Vuln. template', hint: 'ITAdmins' },
        ],
        verify: 'Look for "ESC1" tag in the certipy report.' },
      { id: 's2', title: 'Request impersonating certificate',
        cmdRef: 'certipy-req',
        overrides: { upn: 'administrator@<domain>' },
        rationale: 'Supply SAN UPN=administrator. CA mints a cert for the DA identity.',
        captures: [{ key: 'pfx', label: 'PFX path', hint: 'administrator.pfx' }],
        verify: '`Got certificate with UPN administrator@…`' },
      { id: 's3', title: 'PKINIT → TGT + NT hash',
        cmdRef: 'certipy-auth',
        rationale: 'Authenticate as Administrator with the cert. Certipy also reveals the NT hash via U2U.',
        captures: [
          { key: 'ccache', label: 'TGT ccache', hint: 'administrator.ccache' },
          { key: 'hash',   label: 'NT hash',    ctx: 'hash' },
        ],
        verify: '`Got hash for administrator@…`' },
      { id: 's4', title: 'Confirm DA via DCSync',
        cmdRef: 'secretsdump',
        overrides: { user: 'administrator', password: ':<hash>' },
        rationale: 'Replicate krbtgt to prove DA-equivalent access. Capture krbtgt for future Golden Tickets.',
        captures: [{ key: 'krbtgt', label: 'krbtgt NT hash' }] },
    ],
  },

  {
    id: 'coerce-relay-adcs',
    name: 'Coerce + Relay → ADCS (ESC8)',
    short: 'esc8',
    category: 'active-directory', subcategory: 'priv-esc',
    tactic: 'Initial Access → DA',
    difficulty: 'hard',
    estTime: '20 min',
    objective: 'From unauthenticated foothold on the network: coerce the DC into NTLM auth and relay it to ADCS Web Enrollment to mint a DC certificate.',
    outcome: 'DC$ TGT → DCSync',
    prereqs: [
      'L3 reach to DC and ADCS HTTP',
      'ADCS Web Enrollment enabled, no Channel Binding',
    ],
    mitre: ['T1187', 'T1557.001', 'T1649'],
    steps: [
      { id: 's1', title: 'Confirm ESC8 exposure',
        cmdRef: 'certipy-find',
        rationale: 'Validate WebEnrollment is reachable and the `DomainController` template is enrollable by Domain Computers.' },
      { id: 's2', title: 'Start ntlmrelayx targeting /certsrv',
        cmdRef: 'ntlmrelayx-adcs',
        rationale: 'Leave it running. On successful relay it logs a Base64 PFX for the relayed account.',
        captures: [{ key: 'pfx', label: 'Saved PFX', hint: 'dc01.pfx (auto)' }] },
      { id: 's3', title: 'Coerce DC computer to authenticate',
        cmdRef: 'coercer',
        rationale: 'PetitPotam / MS-RPRN / DFSCoerce forces DC$ to authenticate to our listener.',
        verify: '`Authenticating against http://… as CORP/DC01$ SUCCEED`' },
      { id: 's4', title: 'Convert relayed cert → TGT for DC$',
        cmdRef: 'certipy-auth',
        overrides: { pfx: '<pfx>' },
        rationale: 'PKINIT with the DC$ cert returns a TGT + NT hash for DC$.',
        captures: [
          { key: 'ccache', label: 'DC$ ccache' },
          { key: 'hash',   label: 'DC$ NT hash', ctx: 'hash' },
        ] },
      { id: 's5', title: 'DCSync as DC$',
        cmdRef: 'secretsdump',
        overrides: { user: 'DC01$', password: '' },
        rationale: 'DC computer accounts have replication rights → dump krbtgt and call it.',
        captures: [{ key: 'krbtgt', label: 'krbtgt hash' }] },
    ],
  },

  {
    id: 'asrep-kerb-dcsync',
    name: 'AS-REP → Kerberoast → DCSync',
    short: 'offline',
    category: 'active-directory', subcategory: 'initial-access',
    tactic: 'Credential Access',
    difficulty: 'medium',
    estTime: '30 min + crack',
    objective: 'Offline-only escalation: collect AS-REP hashes, crack one, then Kerberoast and pivot to DCSync.',
    outcome: 'NTDS dump',
    prereqs: ['LDAP visible (anonymous or guest)'],
    mitre: ['T1558.004', 'T1558.003', 'T1003.006'],
    steps: [
      { id: 's1', title: 'Enumerate valid domain users',
        cmdRef: 'kerbrute-userenum',
        captures: [{ key: 'userlist', label: 'Userlist path' }] },
      { id: 's2', title: 'AS-REP roast accounts w/o pre-auth',
        cmdRef: 'getnpusers',
        rationale: 'Accounts with DONT_REQ_PREAUTH leak an AS-REP encrypted with the user key — crackable offline.',
        captures: [{ key: 'asrep', label: 'AS-REP hashes' }] },
      { id: 's3', title: 'Crack AS-REP (hashcat 18200)',
        cmdRef: 'hashcat-ntlm',
        overrides: { mode: '18200', hashfile: '<asrep>' },
        rationale: 'Mode 18200 for AS-REP. One cracked password is enough for the next step.',
        captures: [
          { key: 'user',     label: 'User',     ctx: 'user' },
          { key: 'password', label: 'Password', ctx: 'password' },
        ] },
      { id: 's4', title: 'Kerberoast SPN accounts',
        cmdRef: 'getuserspns',
        rationale: 'Authenticated as the cracked user → request TGS for every SPN.',
        captures: [{ key: 'spn', label: 'SPN hashes' }] },
      { id: 's5', title: 'Crack & find DCSync-capable account',
        cmdRef: 'hashcat-ntlm',
        overrides: { mode: '13100', hashfile: '<spn>' },
        captures: [
          { key: 'dauser', label: 'Privileged user', ctx: 'user' },
          { key: 'dapass', label: 'Password',        ctx: 'password' },
        ] },
      { id: 's6', title: 'DCSync',
        cmdRef: 'secretsdump',
        rationale: 'Run with the high-priv account.' },
    ],
  },

  {
    id: 'rbcd-takeover',
    name: 'RBCD Takeover',
    short: 'rbcd',
    category: 'active-directory', subcategory: 'priv-esc',
    tactic: 'Lateral Movement',
    difficulty: 'medium',
    estTime: '10 min',
    objective: 'Take over a target computer via Resource-Based Constrained Delegation. Write AllowedToActOnBehalfOfOtherIdentity → S4U2Self+Proxy → SYSTEM shell.',
    outcome: 'SYSTEM shell on victim',
    prereqs: [
      'GenericWrite/WriteDACL on victim computer object',
      'MachineAccountQuota > 0 (default 10) — or owned computer',
    ],
    mitre: ['T1134.001', 'T1550.003'],
    steps: [
      { id: 's1', title: 'Confirm ACL via BloodHound',
        cmdRef: 'bloodhound-py',
        rationale: 'Run an AddAllowedToAct edge query to confirm the path.',
        captures: [{ key: 'victim', label: 'Victim host', hint: 'WS01' }] },
      { id: 's2', title: 'Create controlled computer account',
        cmdRef: 'addcomputer',
        rationale: 'Burn one MAQ slot for an SPN we control.',
        captures: [
          { key: 'newhost', label: 'Owned host', hint: 'ATK01' },
          { key: 'newpass', label: 'Password' },
        ] },
      { id: 's3', title: 'Write msDS-AllowedToActOnBehalfOfOtherIdentity',
        cmdRef: 'rbcd-write',
        overrides: { target: '<victim>', attacker: '<newhost>' },
        verify: '`Delegation rights modified successfully!`' },
      { id: 's4', title: 'S4U2Self + S4U2Proxy as Administrator',
        cmdRef: 'getst-s4u',
        overrides: { target: '<victim>.<domain>', impersonate: 'administrator',
                     user: '<newhost>$', password: '<newpass>' },
        rationale: 'Forge a TGS for cifs/<victim>.<domain> as Administrator.',
        captures: [{ key: 'ccache', label: 'admin ccache' }] },
      { id: 's5', title: 'PSExec via ticket',
        cmdRef: 'psexec',
        overrides: { ip: '<victim>.<domain>', user: 'administrator', password: '' },
        rationale: 'Use `-k -no-pass` with KRB5CCNAME pointing at the ccache.' },
    ],
  },

  // ── Service-specific quick chains ────────────────────────
  {
    id: 'smb-foothold',
    name: 'SMB Foothold — Null → Pillage → Auth',
    short: 'smb',
    category: 'service-enum', subcategory: 'smb',
    tactic: 'Initial Access',
    difficulty: 'easy',
    estTime: '15 min',
    objective: 'Flusso SMB standard: prova null/guest, fruga le share per credenziali, poi valida le credenziali per il movimento laterale.',
    outcome: 'Credenziali valide + inventario delle share',
    prereqs: ['Raggiungi SMB (445)'],
    mitre: ['T1135', 'T1083'],
    steps: [
      { id: 's1', title: 'Prova null session',
        cmdRef: 'nxc-smb-null',
        rationale: 'Se le share si elencano con credenziali vuote, potresti già avere accesso in lettura a share interessanti.' },
      { id: 's2', title: 'Elenca le share (cross-check smbclient)',
        cmdRef: 'smbclient-list',
        rationale: 'Ricontrolla con smbclient: a volte mostra share che nxc non vede.' },
      { id: 's3', title: 'Enum completa se hai credenziali',
        cmdRef: 'enum4linux-ng',
        captures: [
          { key: 'user',     label: 'Utente trovato', ctx: 'user' },
          { key: 'share',    label: 'Share interessante' },
        ] },
      { id: 's4', title: 'Spider per file sensibili',
        cmdRef: 'nxc-smb-spider',
        rationale: 'Cerca credenziali in chiaro nei documenti condivisi (config, script, .xlsx).',
        captures: [{ key: 'password', label: 'Password trovata', ctx: 'password' }] },
      { id: 's5', title: 'Check password GPP',
        cmdRef: 'nxc-smb-gpp',
        rationale: 'Le vecchie Group Policy Preferences lasciano spesso cpassword su SYSVOL.' },
    ],
  },

  {
    id: 'mssql-rce',
    name: 'MSSQL → RCE',
    short: 'mssql',
    category: 'service-enum', subcategory: 'mssql',
    tactic: 'Exploitation',
    difficulty: 'easy',
    estTime: '10 min',
    objective: 'Escalation MSSQL standard: login → verifica sysadmin → xp_cmdshell. Se non sei sysadmin, prova IMPERSONATE.',
    outcome: 'RCE come account del servizio SQL',
    prereqs: ['Credenziali MSSQL valide'],
    mitre: ['T1190', 'T1059'],
    steps: [
      { id: 's1', title: 'Connessione',
        cmdRef: 'mssql-login' },
      { id: 's2', title: 'Verifica ruolo',
        rationale: 'SELECT IS_SRVROLEMEMBER(\'sysadmin\'): se torna 1, xp_cmdshell è subito disponibile.' },
      { id: 's3', title: 'xp_cmdshell RCE (via sysadmin)',
        cmdRef: 'mssql-xpcmdshell',
        overrides: { cmd: 'whoami' } },
      { id: 's4', title: 'Oppure: impersona sa (senza sysadmin)',
        cmdRef: 'mssql-impersonate',
        rationale: 'Se non sei sysadmin: SELECT dei permessi IMPERSONATE, poi EXECUTE AS LOGIN.' },
    ],
  },

  {
    id: 'lfi-to-rce',
    name: 'LFI → Log Poisoning → RCE',
    short: 'lfi',
    category: 'vuln-analysis', subcategory: 'web-app-testing',
    tactic: 'Exploitation',
    difficulty: 'medium',
    estTime: '20 min',
    objective: 'Trasforma una Local File Inclusion in esecuzione di codice avvelenando un log con PHP e poi includendolo.',
    outcome: 'RCE come utente del web server',
    prereqs: ['Parametro vulnerabile a LFI', 'Accesso in lettura a un log (Apache/Nginx/auth)'],
    mitre: ['T1190', 'T1505.003'],
    steps: [
      { id: 's1', title: 'Conferma la LFI',
        cmdRef: 'lfi',
        rationale: 'Leggi `/etc/passwd` per confermare il path traversal e capire la profondità.' },
      { id: 's2', title: 'Inietta PHP nel log (User-Agent)',
        cmdRef: 'lfi-logpoison', variant: 'default',
        rationale: 'Il payload nello User-Agent finisce nell’access.log del web server.' },
      { id: 's3', title: 'Includi il log ed esegui',
        cmdRef: 'lfi-logpoison', variant: 'trigger',
        rationale: 'Includendo il log via LFI, il PHP iniettato viene eseguito; `cmd=` passa il comando.',
        captures: [{ key: 'ip', label: 'Target', ctx: 'ip' }] },
    ],
  },

  {
    id: 'kerberoast-crack',
    name: 'Kerberoast → Crack → Lateral',
    short: 'kerb',
    category: 'active-directory', subcategory: 'initial-access',
    tactic: 'Credential Access',
    difficulty: 'medium',
    estTime: '30 min',
    objective: 'Richiedi i TGS degli account con SPN, crackali offline e riusa la password trovata per muoverti.',
    outcome: 'Password di un service account (spesso privilegiato)',
    prereqs: ['Credenziali di dominio valide'],
    mitre: ['T1558.003', 'T1110.002'],
    steps: [
      { id: 's1', title: 'Richiedi i TGS (Kerberoast)',
        cmdRef: 'getuserspns',
        rationale: 'Salva gli hash in `kerb.txt`; i service account hanno spesso password deboli.' },
      { id: 's2', title: 'Cracka offline',
        cmdRef: 'hashcat-ntlm', overrides: { mode: '13100', hashfile: 'kerb.txt' },
        rationale: 'Mode `13100` = TGS Kerberoast.',
        captures: [
          { key: 'user',     label: 'Service account', ctx: 'user' },
          { key: 'password', label: 'Password craccata', ctx: 'password' },
        ] },
      { id: 's3', title: 'Riusa le credenziali',
        cmdRef: 'psexec',
        rationale: 'Prova la password sui servizi (SMB/WinRM): se il service account è admin da qualche parte, è game over.' },
    ],
  },

  {
    id: 'responder-relay',
    name: 'Responder → NTLM Relay → Shell',
    short: 'relay',
    category: 'active-directory', subcategory: 'initial-access',
    tactic: 'Credential Access',
    difficulty: 'medium',
    estTime: '25 min',
    objective: 'Cattura NetNTLMv2 avvelenando LLMNR/NBT-NS; crackalo, oppure rilancialo (relay) verso host senza SMB signing per una shell.',
    outcome: 'Hash NetNTLMv2 o shell su un host senza signing',
    prereqs: ['Posizione in rete (stesso segmento delle vittime)'],
    mitre: ['T1557.001', 'T1212'],
    steps: [
      { id: 's1', title: 'Trova i target senza SMB signing',
        rationale: 'Genera la lista relay: `nxc smb <range> --gen-relay-list targets.txt` (signing:False).' },
      { id: 's2', title: 'Avvelena e cattura',
        cmdRef: 'responder', variant: 'default',
        rationale: 'Cattura i NetNTLMv2 di chi cerca host inesistenti.',
        captures: [{ key: 'hash', label: 'NetNTLMv2 catturato', ctx: 'hash' }] },
      { id: 's3', title: 'Oppure rilancia (relay)',
        cmdRef: 'ntlmrelayx-smb', variant: 'default',
        rationale: 'Disabilita SMB/HTTP in `Responder.conf`, poi relaya verso i target senza signing per una shell o un dump SAM.' },
    ],
  },

  {
    id: 'sqli-to-creds',
    name: 'SQLi → Dump → Login',
    short: 'sqli',
    category: 'vuln-analysis', subcategory: 'web-app-testing',
    tactic: 'Credential Access',
    difficulty: 'easy',
    estTime: '20 min',
    objective: 'Da un’iniezione SQL estrai le credenziali applicative, crackale se hashate e riusale per autenticarti.',
    outcome: 'Credenziali valide dall’applicazione',
    prereqs: ['Parametro iniettabile (SQLi)'],
    mitre: ['T1190', 'T1110.002'],
    steps: [
      { id: 's1', title: 'Conferma l’iniezione',
        cmdRef: 'sqli-detect',
        rationale: 'Boolean o time-based per confermare prima di automatizzare.' },
      { id: 's2', title: 'Enumera i database',
        cmdRef: 'sqlmap', variant: 'default' },
      { id: 's3', title: 'Dumpa la tabella utenti',
        cmdRef: 'sqlmap', variant: 'dump',
        captures: [
          { key: 'user',     label: 'Utente trovato', ctx: 'user' },
          { key: 'password', label: 'Password/hash', ctx: 'password' },
        ] },
      { id: 's4', title: 'Cracka se hashate, poi riusa',
        cmdRef: 'hashcat-ntlm', overrides: { mode: '0' },
        rationale: 'Identifica il tipo di hash (es. `0` MD5) e crackalo; poi riusa le credenziali su login/SSH/SMB.' },
    ],
  },
];

window.CHAINS = CHAINS;
